metrics_enabled: false
debug: true
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - org.skife
    - xx-responses
    - com.hello

common_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

insights_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

redshift:
  driverClass: org.postgresql.Driver
  user: admin_tool
  password: enciphers56491Zeppelins
  url: jdbc:postgresql://sensors2.cy7n0vzxfedi.us-east-1.redshift.amazonaws.com:5439/sensors1
  properties:
    charSet: UTF-8
  initialSize: 2
  minSize: 2
  maxSize: 4

store_db:
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku
  properties:
    charSet: UTF-8
  initialSize: 2
  minSize: 2
  maxSize: 4

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 6666
  adminConnectors:
    - type: http
      port: 6667
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/suripu-admin/suripu-admin-access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /var/log/suripu-admin/suripu-admin-access-%d{yyyy-MM-dd}.log.gz
        archivedFileCount: 7
      - type: papertrail
        host: logs2.papertrailapp.com
        port: 11366
        ident: suripu-admin-dev

logging:
  level: INFO
  loggers:
    com.hello.suripu.admin: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/suripu-admin/suripu-admin.log
      archivedLogFilenamePattern: /var/log/suripu-admin/suripu-admin-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-admin-dev
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    audio_features : audio_features
    activity_stream : activity_stream
    registrations: registrations
    encode_audio : encode_audio
    batch_pill_data : batch_pill_data
    sense_sensors_data : sense_sensors_data

redis:
  host: localhost
  port: 6379

dynamodb:
  region: us-east-1
  tables:
    alarm_info : alarm_info
    device_data : sense_data
    features : features
    file_manifest: file_manifest
    firmware_upgrade_path: fw_upgrade_path
    firmware_versions : prod_firmware_versions_mapping
    insights: insights
    insights_last_seen: insights_last_seen
    marketing_insights_seen : marketing_insights_seen
    ota_history : ota_history
    password_reset : password_reset
    pill_key_store : pill_key_store
    pill_last_seen: pill_last_seen
    pill_heartbeat: pill_heartbeat
    pill_data: pill_data
    sense_events : sense_events
    sense_key_store : key_store
    sense_last_seen : sense_last_seen
    sense_prefix : sense
    sync_response_commands : response_commands
    tags: tags
    teams : teams
    timezone_history : timezone_history
    ring_time_history: ring_history_by_account
    smart_alarm_log: smart_alarm_log
    calibration: calibration
    sleep_stats : sleep_stats
    preferences : preferences
    profile_photo: profile_photo
    sleep_score : sleep_score
    wifi_info : wifi_info



  endpoints:
    alarm_info : http://dynamodb.us-east-1.amazonaws.com
    device_data : http://dynamodb.us-east-1.amazonaws.com
    features : http://dynamodb.us-east-1.amazonaws.com
    file_manifest: http://dynamodb.us-east-1.amazonaws.com
    firmware_upgrade_path : http://dynamodb.us-east-1.amazonaws.com
    firmware_versions : http://dynamodb.us-east-1.amazonaws.com
    insights: http://dynamodb.us-east-1.amazonaws.com
    insights_last_seen: http://dynamodb.us-east-1.amazonaws.com
    ota_history : http://dynamodb.us-east-1.amazonaws.com
    marketing_insights_seen : http://dynamodb.us-east-1.amazonaws.com
    password_reset : http://dynamodb.us-east-1.amazonaws.com
    pill_key_store : http://dynamodb.us-east-1.amazonaws.com
    pill_last_seen : http://dynamodb.us-east-1.amazonaws.com
    pill_heartbeat : http://dynamodb.us-east-1.amazonaws.com
    pill_data: http://dynamodb.us-east-1.amazonaws.com
    sense_events : http://dynamodb.us-east-1.amazonaws.com
    sense_key_store : http://dynamodb.us-east-1.amazonaws.com
    sense_last_seen : http://dynamodb.us-east-1.amazonaws.com
    sense_prefix : http://dynamodb.us-east-1.amazonaws.com
    sync_response_commands : http://dynamodb.us-east-1.amazonaws.com
    tags: http://dynamodb.us-east-1.amazonaws.com
    teams : http://dynamodb.us-east-1.amazonaws.com
    timezone_history : http://dynamodb.us-east-1.amazonaws.com
    smart_alarm_log: http://dynamodb.us-east-1.amazonaws.com
    ring_time_history: http://dynamodb.us-east-1.amazonaws.com
    calibration: http://dynamodb.us-east-1.amazonaws.com
    sleep_stats : http://dynamodb.us-east-1.amazonaws.com
    preferences : http://dynamodb.us-east-1.amazonaws.com
    profile_photo : http://dynamodb.us-east-1.amazonaws.com
    sleep_score : http://dynamodb.us-east-1.amazonaws.com
    wifi_info : http://dynamodb.us-east-1.amazonaws.com


sleep_score_version: v_0_1
sleep_stats_version: v_0_2

token_expiration: 3600