metrics_enabled: true
debug: false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - org.skife
    - xx-responses
    - com.hello

sensors_db:
  driverClass: org.postgresql.Driver
  user: sensors
  password: hello-sensors
  url: jdbc:postgresql://sensors-2-replica-1.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/sensors1
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 2

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 8

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

common_db:
  driverClass: org.postgresql.Driver
  user: common
  password: hello-common
  url: jdbc:postgresql://common.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/common
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

insights_db:
  driverClass: org.postgresql.Driver
  user: common
  password: hello-common
  url: jdbc:postgresql://common.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/common
  properties:
    hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect


server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 6666
  adminConnectors:
    - type: http
      port: 6667
  requestLog:
    timeZone: UTC
    appenders:
      - type: file
        currentLogFilename: /var/log/suripu-admin/suripu-admin-access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: /var/log/suripu-admin/suripu-admin-access-%d{yyyy-MM-dd}.log.gz
        archivedFileCount: 7
      - type: papertrail
        host: logs2.papertrailapp.com
        port: 11366
        ident: suripu-admin-prod

logging:
  level: INFO
  loggers:
    com.hello.suripu: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/suripu-admin/suripu-admin.log
      archivedLogFilenamePattern: /var/log/suripu-admin/suripu-admin-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-admin-prod
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    audio_features : audio_features
    activity_stream : activity_stream
    registrations: registrations
    encode_audio : encode_audio
    batch_pill_data : batch_pill_data
    sense_sensors_data : sense_sensors_data

kinesis_logger:
  stream_name: logs
  enabled : false
  buffer_size: 100
  origin: suripu-admin

redis:
  host: stats.xoe7je.0001.use1.cache.amazonaws.com
  port: 6379

dynamodb:
  region: us-east-1
  tables:
    alarm_info : prod_alarm_info
    features : features
    firmware_upgrade_path : fw_upgrade_path
    firmware_versions : prod_firmware_versions_mapping
    ota_history : ota_history
    password_reset : prod_password_reset
    pill_key_store : pill_key_store
    pill_last_seen : prod_pill_last_seen
    sense_events : prod_sense_events
    sense_key_store : key_store
    sense_last_seen : prod_sense_last_seen
    sense_prefix : prod_sense
    sync_response_commands : prod_response_commands
    teams : teams
    timezone_history : prod_timezone_history
    ring_time_history: prod_ring_history_by_account
    smart_alarm_log: prod_smart_alarm_log
    calibration: prod_calibration
    insights : prod_insights
    sleep_stats : prod_sleep_stats
    preferences : prod_preferences
    sleep_score : prod_sleep_score

  endpoints:
      alarm_info : http://dynamodb.us-east-1.amazonaws.com
      features : http://dynamodb.us-east-1.amazonaws.com
      firmware_upgrade_path : http://dynamodb.us-east-1.amazonaws.com
      firmware_versions : http://dynamodb.us-east-1.amazonaws.com
      ota_history : http://dynamodb.us-east-1.amazonaws.com
      password_reset : http://dynamodb.us-east-1.amazonaws.com
      pill_key_store : http://dynamodb.us-east-1.amazonaws.com
      pill_last_seen : http://dynamodb.us-east-1.amazonaws.com
      sense_events : http://dynamodb.us-east-1.amazonaws.com
      sense_key_store : http://dynamodb.us-east-1.amazonaws.com
      sense_last_seen : http://dynamodb.us-east-1.amazonaws.com
      sense_prefix : http://dynamodb.us-east-1.amazonaws.com
      sync_response_commands : http://dynamodb.us-east-1.amazonaws.com
      teams : http://dynamodb.us-east-1.amazonaws.com
      timezone_history : http://dynamodb.us-east-1.amazonaws.com
      smart_alarm_log: http://dynamodb.us-east-1.amazonaws.com
      ring_time_history: http://dynamodb.us-east-1.amazonaws.com
      calibration: http://dynamodb.us-east-1.amazonaws.com
      insights : http://dynamodb.us-east-1.amazonaws.com
      sleep_stats : http://dynamodb.us-east-1.amazonaws.com
      preferences : http://dynamodb.us-east-1.amazonaws.com
      sleep_score : http://dynamodb.us-east-1.amazonaws.com

sleep_score_version: v_0_1
sleep_stats_version: v_0_2

token_expiration: 300

